### ISSUE TITLE
CREATE USER and GRANT PRIVILEGE via root account says "Access Denied for user Root@%"

### ISSUE THREAD

**Issue by syedrakib** [sequelpro/sequelpro#2229]
I logged in with root user and then tried to create a new user via `Database>UserAccounts`.

It says `"Access denied for user 'root@%' (using password: YES)"`

![screen shot 2015-09-16 at 8 26 49 pm](https://cloud.githubusercontent.com/assets/975768/9907617/d9fdfe0c-5cb1-11e5-8298-493b6f009d55.png)

I get the same error when i try to Grant privileges to the user from `Database>UserAccounts` .

But when i reopen the `Database>UserAccounts` dialog again, i see that the new user has been actually created and the desired privileges have actually been granted.

N.B. creating a user and granting privileges works perfectly fine when executing MySQL query commands in SequelPro.

**Comment by rowanbeentje** [comment]
I haven't seen this for a while - are you still able to reproduce this issue in http://www.sequelpro.com/blog/2015.08/sequel-pro-1-1-rc2/ ?

**Comment by syedrakib** [comment]
still happens in 1.1RC-2

**Comment by dmoagx** [comment]
I only know that message as a connection error.
Does your user have limits on max. number of connections?
Open the Query Console window and try to run the commands Sequel Pro executes, manually to check which one fails.

**Comment by syedrakib** [comment]
There is no limit on max_connections or max_user_connections. Only 1 or 2 people trying to access this test RDS DB. `CREATE USER` works by query console. `GRANT PRIVILEGES` works be query console. Just not when using the SequelPro GUI.

**Comment by dmoagx** [comment]
I think you are confusing the Query console and the Query editor.
Query editor is where you type queries.
Query console is where Sequel Pro shows all queries it did send. Open the console from View > Show Console.
Copy those queries the User Manager made and execute them one-by-one. Post the **exact** query that failed.

**Comment by syedrakib** [comment]
right.... i got it mixed up there..... thanks for clarifying.

yes you are right. Following are the series of SQLs that are executed upon creating a new  user.

    /* 6:04:35 AM myRDS */ CREATE USER 'alice'@'localhost' IDENTIFIED BY 'ALiCe';
    /* 6:04:36 AM myRDS */ UPDATE mysql.user SET max_questions = 0, max_updates = 0, max_connections = 0 WHERE User = 'alice' AND Host = 'localhost';
    #### PROBLEM OCCURS IN THE REVOKE STATEMENT #### /* 6:04:36 AM myRDS */ REVOKE CREATE ROUTINE, CREATE VIEW, CREATE USER, ALTER, SHOW VIEW, CREATE, ALTER ROUTINE, EVENT, SUPER, INSERT, RELOAD, SELECT, DELETE, FILE, SHOW DATABASES, TRIGGER, SHUTDOWN, REPLICATION CLIENT, GRANT OPTION, PROCESS, REFERENCES, UPDATE, DROP, REPLICATION SLAVE, EXECUTE, LOCK TABLES, CREATE TEMPORARY TABLES, INDEX ON *.* FROM 'alice'@'localhost';
    /* 6:04:37 AM myRDS */ FLUSH PRIVILEGES;


Viewing the privileges on Root@% user shows:

![screen shot 2015-09-18 at 6 14 41 am](https://cloud.githubusercontent.com/assets/975768/9949301/b528445e-5dcc-11e5-8fb4-334dbce3de64.png)

**Comment by dmoagx** [comment]
OK, can reproduce that.
If your user lacks those rights then trying to revoke them will fail.

So we basically have to check which rights the current user has, disable the checkboxes for the others and don't add them to the statement.

**Comment by syedrakib** [comment]
can you please clarify? which ones do you mean to disable when you say _"disable the checkboxes for the others"_ and which ones do you mean not to add when you say _"don't add them"_?

**Comment by dmoagx** [comment]
I'm talking about what we have to change in Sequel Pro.
There is nothing you can do about this at the moment (except not using the User Manager).

**Comment by syedrakib** [comment]
i see... ok... thanks for identifying the bug then.

on a sidenote, i am curious why this root user would not have some privileges. I am spinning off an AWS RDS instance and i get a root user with that instance... and ideally, that root user "should" have all privileges on it from the beginning. Right?

**Comment by dmoagx** [comment]
I guess that is specific to Amazon RDS. Most likely they have customized MySQL to their needs.
Also a right like "File" would be a bad idea for Amazon as it allows to read physical files on the MySQL server host (to which I assume you normally don't have access via RDS).

**Comment by ambroselittle** [comment]
I have confirmed this is an issue with Google Cloud SQL as well. Is there any update on this? 

I had contact Google support, and this is their response:

> After reviewing the information provided, I noticed that on the revoke command, you’re adding the privileges ‘SUPER’ and ‘FILE’.As explained in here[1], on a managed Cloud SQL instance, root users don’t have this privilege. This also will explain why it’s not possible to use ‘GRANT ALL PRIVILEGES’[2]. I tested the command the way you provided, and I got a similar error on MySQL client, as I don’t have a Mac to test  Sequel Pro.
> 
> So, you can add multiple permissions to your users, as long as they don’t include SUPER’ and ‘FILE’.
> 
> [1] https://cloud.google.com/sql/docs/users-mysql
> [2] https://cloud.google.com/sql/faq#grantall
> 

Is there any workaround besides manually issuing commands in the query editor?  Can I help get this fixed in Sequel Pro somehow? Seems important for the two biggest cloud vendors.

**Comment by dmoagx** [comment]
Part of the solution and an easy fix for creating new users would be to just not run any revoke statements at all, since MySQL doc states:
> An account when first created has no privileges.
http://dev.mysql.com/doc/refman/5.7/en/create-user.html
back to 5.0:
> ... creates a new record in the mysql.user table that has no privileges. 
http://web.archive.org/web/20051101003528/http://dev.mysql.com/doc/refman/5.0/en/create-user.html

For updating users the change would be more difficult.
I assume that Sequel Pro currently only tries to match the checkboxes in the GUI with `GRANT`/`REVOKE` queries, because it was previously not easily possible to detect changed values.
However, because of a change I made previously we can now actually use `-[NSManagedObject changedValues]` and only update the values that actually changed.

**Comment by ambroselittle** [comment]
Let me know if you have a build you want me to try out.

**Comment by abhibeckert** [comment]
@ambroselittle nightly build system is non-operational right now.

Here's a fresh build: [Sequel Pro.app.zip](https://github.com/sequelpro/sequelpro/files/635621/Sequel.Pro.app.zip)

**Comment by ambroselittle** [comment]
Okay. I tried to make a new user. Just clicked Users, the plus sign, then name and pass.

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(null) AS (null)' at line 1
```

Here are the commands it tried:
```
/* 10:44:17 PM Test SQL */ CREATE USER 'ambrose'@'localhost' IDENTIFIED WITH (null) AS (null);
/* 10:44:17 PM Test SQL */ FLUSH PRIVILEGES;
```

This is Cloud SQL 2nd Gen with MySQL 5.7.

**Comment by ambroselittle** [comment]
BTW, if you haven't already, you can sign up for a free trial with Google Cloud. They give you $300 credit. If you want to try it out yourself.

**Comment by abhibeckert** [comment]
Hmmm @ambroselittle I didn't write the code (and I hope dmoagx is sleeping at 4am), but that error doesn't look like it's related to this fix.

Can you try with this older build? https://sequelpro.com/Sequel_Pro_r50a0f18540.dmg

**Comment by ambroselittle** [comment]
Same thing with that one. I may be doing something wrong. :)

**Comment by abhibeckert** [comment]
I'm sure @dmoagx will get back to you tomorrow with some suggestions.

**Comment by dmoagx** [comment]
That seems to be a bug introduced in the fix for #2418

**Comment by dmoagx** [comment]
So this should be working now, but I'll leave this issue, because I still think we should implement what I mentioned before:
> So we basically have to check which rights the current user has, disable the checkboxes for the others (...)

**Comment by ambroselittle** [comment]
Okay, @dmoagx, I'm happy to test the build sometime if you like. If I'm reading this right that at least it should work if I don't try to choose to do what I am not allowed to do.

**Comment by fxer** [comment]
Is there a nightly build or something similar with this fix?

As above, I notice any *additional* privileges I apply to a user as root get applied, in spite of the error message. however *removing* privileges does not work, you get the error message and the user is not updated.

**Comment by dmoagx** [comment]
https://sequelpro.com/test-builds

**Comment by scolson** [comment]
Not to "me too" this issue to horribly... but this is still an issue in the latest stable release despite being fixed for a year now.

Is there any chance of stamping out a new version? There have been a lot of bugs fixed in the past two or so years since the last dot release. I'd hate to switch to nightlies and risk auto updating to a broken nightly on occasion.

**Comment by mlody1039** [comment]
I found work around this.

Log in as root via Sqruel Pro

got to users
got to root

You will see
%
127.0.0.1
localhost

You will see localhost have grant option.
All you need to do is 

Rename % to test
and rename localhost to % and press apply

After disconnect from the session go to ssh
run this command

grant all privileges on *.* to 'root'@'%' identified by 'NEWPASSWORD';

and log in to Sequel Pro and you have granted permission :)
