### ISSUE TITLE
Sequel Pro did no show real error message

### ISSUE THREAD

**Issue by xiangbohua** [sequelpro/sequelpro#3343]
- Sequel Pro Version:Test Build 5426(19180f9d)
- macOS Version:10.14.2
- MySQL Version:5.6.20-log (show also other Version)

**Description**
When execution an worry sql  Sequel Pro did not show the real error message from mysql-server but only show : "their was no errors."
Such as select from a worry filed name from a table.
This problem was not shown ever time. So i don't know what the reason is.
By the way. The query window some time scrolled out of the top frame so I could't see the first line of my sql script.

**Steps To Reproduce**
1.open software
2.connect to a server
3.open the Query window
4.execute an error script such as 
create table table111
(
a VARCHAR(65535)

)charset = latin1 ENGINE = InnoDB

**Expected Behaviour**
After execute an error script i should see the real error message. In the case above i should see : Row size too large ... But some time Sequel Pro would show: there was no errors. So i could't know the real reason why i was failure.

**Additional Context**
nothing

**Comment by dmoagx** [comment]
That sounds like #3271 to me, which should already be fixed (at least I haven't heard any other feedback about it).

**Comment by neoramos** [comment]
I'm having the same issue as xiangbohua

**Comment by xiangbohua** [comment]
@dmoagx This problem was keep shown at the test build 16180f9d3c on my machine. But is not a big problem. I'm waiting the newest test build.And i have got a new problem about UI display. 
The UI was going to a mess after I have open two  connections taps and switch one to other one.It's looks like worry Encoding. Please see this image:
![default](https://user-images.githubusercontent.com/10529889/50751021-c6b04500-1282-11e9-9d2c-83098c64e2a0.png)

**Comment by gthornock** [comment]
I'm still seeing this issue at least for some errors in nightly build d78907bd (from 2-3 days ago).  Specifically, I never see any error message for incorrect field names - e.g. "select `field_that_does_not_exist` from my_table" will return no results, but also no error messages.

**Comment by dominicgermain** [comment]
There is many type of errors from the server that are ignored my SequelPro.

Example :
`select 1, 2, 3 from dual union select 4, 5 from dual;`

Should get something like : 
`ERROR 1222 (21000): The used SELECT statements have a different number of columns`

**Comment by wlkns** [comment]
I am still getting this issue on MySQL 5.7.4, Sequel Pro nightly build 5446 (97c1b857).

Query returns "There were no errors" but should have data. Issuing `SHOW ERRORS` shows the correct error.
